
import React from "react";
import ScrollToTop from "../components/ScrollToTop";
import Starfield from "../components/Starfield";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Em's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/em_logo.png", sizes: "32x32", type: "image/png" },
      { url: "/em_logo.png", sizes: "16x16", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ position: "relative", minHeight: "100vh", overflowX: "hidden" }}
      >
        <Starfield />
        <ScrollToTop />
        {children}
      </body>
    </html>
  );
}
